{
   u'user_alert_dialog':{
      u'604854':{
         u'$version':-30762,
         u'dialog_id':u'confirm-pairing',
         u'dialog_data':u'',
         u'$timestamp':1389479057121         L
      }
   },
   u'user_settings':{
      u'604854':{
         u'lang':u'en_US',
         u'tos_current_version':1381190400000         L,
         u'tos_accepted_version':1381190400000         L,
         u'tos_minimum_version':1381190400000         L,
         u'receive_marketing_emails':True,
         u'receive_nest_emails':True,
         u'email_verified':True,
         u'max_thermostats':10,
         u'max_smoke_detectors':36,
         u'max_thermostats_per_structure':10,
         u'max_structures':2,
         u'max_smoke_detectors_per_structure':18,
         u'$version':10462,
         u'$timestamp':1389478538295         L,
         u'receive_support_emails':True
      }
   },
   u'schedule':{
      u'02AA01AC371305HK':{
         u'ver':2,
         u'name':u'Nest Current Schedule',
         u'days':{
            u'1':{
               u'1':{
                  u'touched_tzo':-25200,
                  u'temp':23.889,
                  u'entry_type':u'setpoint',
                  u'touched_at':1405668455,
                  u'time':41400,
                  u'touched_by':1,
                  u'type':u'COOL'
               },
               u'0':{
                  u'touched_tzo':-25200,
                  u'temp':22.87,
                  u'entry_type':u'continuation',
                  u'touched_at':1410852419,
                  u'time':0,
                  u'touched_by':1,
                  u'type':u'COOL'
               },
               u'2':{
                  u'touched_tzo':-25200,
                  u'temp':22.87,
                  u'entry_type':u'setpoint',
                  u'touched_at':1406359655,
                  u'time':64800,
                  u'touched_by':1,
                  u'type':u'COOL'
               }
            },
            u'0':{
               u'1':{
                  u'touched_tzo':-25200,
                  u'temp':23.889,
                  u'entry_type':u'setpoint',
                  u'touched_at':1405668455,
                  u'time':41400,
                  u'touched_by':1,
                  u'type':u'COOL'
               },
               u'0':{
                  u'touched_tzo':-25200,
                  u'temp':22.819,
                  u'entry_type':u'continuation',
                  u'touched_at':1410852419,
                  u'time':0,
                  u'touched_by':1,
                  u'type':u'COOL'
               },
               u'2':{
                  u'touched_tzo':-25200,
                  u'temp':22.87,
                  u'entry_type':u'setpoint',
                  u'touched_at':1406359655,
                  u'time':64800,
                  u'touched_by':1,
                  u'type':u'COOL'
               }
            },
            u'3':{
               u'1':{
                  u'touched_tzo':-25200,
                  u'temp':23.889,
                  u'entry_type':u'setpoint',
                  u'touched_at':1405621892,
                  u'time':41400,
                  u'touched_by':3,
                  u'type':u'COOL'
               },
               u'0':{
                  u'touched_tzo':-25200,
                  u'temp':22.749,
                  u'entry_type':u'continuation',
                  u'touched_at':1410852419,
                  u'time':0,
                  u'touched_by':1,
                  u'type':u'COOL'
               },
               u'2':{
                  u'touched_tzo':-25200,
                  u'temp':22.87,
                  u'entry_type':u'setpoint',
                  u'touched_at':1406359655,
                  u'time':64800,
                  u'touched_by':1,
                  u'type':u'COOL'
               }
            },
            u'2':{
               u'1':{
                  u'touched_tzo':-25200,
                  u'temp':23.889,
                  u'entry_type':u'setpoint',
                  u'touched_at':1405668455,
                  u'time':41400,
                  u'touched_by':1,
                  u'type':u'COOL'
               },
               u'0':{
                  u'touched_tzo':-25200,
                  u'temp':22.87,
                  u'entry_type':u'continuation',
                  u'touched_at':1410852419,
                  u'time':0,
                  u'touched_by':1,
                  u'type':u'COOL'
               },
               u'2':{
                  u'touched_tzo':-25200,
                  u'temp':22.749,
                  u'entry_type':u'setpoint',
                  u'touched_at':1407361806,
                  u'time':53100,
                  u'touched_by':2,
                  u'type':u'COOL'
               }
            },
            u'5':{
               u'0':{
                  u'touched_tzo':-25200,
                  u'temp':22.819,
                  u'entry_type':u'continuation',
                  u'touched_at':1410852419,
                  u'time':0,
                  u'touched_by':1,
                  u'type':u'COOL'
               }
            },
            u'4':{
               u'1':{
                  u'touched_tzo':-25200,
                  u'temp':23.889,
                  u'entry_type':u'setpoint',
                  u'touched_at':1405668455,
                  u'time':41400,
                  u'touched_by':1,
                  u'type':u'COOL'
               },
               u'0':{
                  u'touched_tzo':-25200,
                  u'temp':22.87,
                  u'entry_type':u'continuation',
                  u'touched_at':1410852419,
                  u'time':0,
                  u'touched_by':1,
                  u'type':u'COOL'
               },
               u'2':{
                  u'touched_tzo':-25200,
                  u'temp':22.819,
                  u'entry_type':u'setpoint',
                  u'touched_at':1406359655,
                  u'time':55800,
                  u'touched_by':1,
                  u'type':u'COOL'
               }
            },
            u'6':{
               u'0':{
                  u'touched_tzo':-25200,
                  u'temp':22.819,
                  u'entry_type':u'continuation',
                  u'touched_at':1410852419,
                  u'time':0,
                  u'touched_by':1,
                  u'type':u'COOL'
               }
            }
         },
         u'schedule_mode':u'COOL',
         u'$version':20117,
         u'$timestamp':1410852422520         L
      }
   },
   u'track':{
      u'02AA01AC371305HK':{
         u'$version':-30680,
         u'last_ip':u'63.230.130.31',
         u'last_connection':1410891468747         L,
         u'$timestamp':1410891468747         L,
         u'online':True
      }
   },
   u'user':{
      u'604854':{
         u'structure_memberships':[
            {
               u'roles':[
                  u'owner'
               ],
               u'structure':u'structure.dbd0c390-7b0d-11e3-9da1-12313b0281cc'
            }
         ],
         u'name':u'elijahe@gmail.com',
         u'$version':4267,
         u'structures':[
            u'structure.dbd0c390-7b0d-11e3-9da1-12313b0281cc'
         ],
         u'email':u'elijahe@gmail.com',
         u'$timestamp':1389478520396         L
      }
   },
   u'demand_response':{
      u'02AA01AC371305HK':{
         u'$version':-1,
         u'$timestamp':1
      }
   },
   u'device_alert_dialog':{
      u'02AA01AC371305HK':{
         u'$version':-30706,
         u'dialog_id':u'confirm-pairing',
         u'dialog_data':u'',
         u'$timestamp':1389479057121         L
      }
   },
   u'link':{
      u'02AA01AC371305HK':{
         u'$version':20746,
         u'structure':u'structure.dbd0c390-7b0d-11e3-9da1-12313b0281cc',
         u'$timestamp':1389479057121         L
      }
   },
   u'message_center':{
      u'604854':{
         u'$version':-1,
         u'messages':[

         ],
         u'$timestamp':1325379661000         L
      }
   },
   u'tuneups':{
      u'02AA01AC371305HK':{
         u'$version':-1,
         u'$timestamp':1
      }
   },
   u'device':{
      u'02AA01AC371305HK':{
         u'heat_pump_comp_threshold':-31.5,
         u'backplate_model':u'Backplate-2.7',
         u'gear_threshold_low':0.0,
         u'lower_safety_temp_enabled':True,
         u'postal_code':u'99208',
         u'learning_mode':True,
         u'country_code':u'US',
         u'star_type':u'unknown',
         u'heat_x3_source':u'gas',
         u'fan_timer_duration':1800,
         u'backplate_serial_number':u'02BA02AC381300UR',
         u'hvac_wires':u'Heat,
         Cool,
         Fan,
         Common Wire,
         Rh',
         u'humidifier_type':u'unknown',
         u'sunlight_correction_active':False,
         u'logging_priority':u'informational',
         u'temperature_lock':False,
         u'auto_away_reset':False,
         u'dual_fuel_breakpoint_override':u'none',
         u'has_x3_heat':False,
         u'cooling_x2_delivery':u'unknown',
         u'maint_band_lower':0.56,
         u'device_locale':u'en_US',
         u'learning_time':1619,
         u'has_fan':True,
         u'pin_rh_description':u'power',
         u'has_x2_alt_heat':False,
         u'leaf_away_high':23.889,
         u'heat_x2_source':u'gas',
         u'aux_heat_source':u'electric',
         u'filter_changed_date':0,
         u'equipment_type':u'electric',
         u'dehumidifier_orientation_selected':u'unknown',
         u'forced_air':True,
         u'aux_lockout_leaf':10.0,
         u'filter_reminder_level':0,
         u'humidifier_state':False,
         u'error_code':u'',
         u'switch_system_off':False,
         u'has_x2_cool':False,
         u'serial_number':u'02AA01AC371305HK',
         u'hvac_pins':u'W1,
         Y1,
         C,
         Rh,
         G',
         u'fan_cooling_enabled':False,
         u'heat_pump_comp_threshold_enabled':False,
         u'pin_star_description':u'none',
         u'sunlight_correction_enabled':True,
         u'learning_days_completed_cool':65,
         u'away_temperature_low_enabled':True,
         u'note_codes':[

         ],
         u'leaf_threshold_heat':1000.0,
         u'y2_type':u'unknown',
         u'leaf':True,
         u'auto_dehum_enabled':False,
         u'alt_heat_x2_source':u'gas',
         u'has_humidifier':False,
         u'gear_threshold_high':0.0,
         u'current_schedule_mode':u'COOL',
         u'backplate_bsl_info':u'BSL',
         u'fan_cooling_readiness':u'ready',
         u'battery_level':3.9,
         u'humidity_control_lockout_end_time':0,
         u'ob_persistence':True,
         u'hvac_safety_shutoff_active':False,
         u'schedule_learning_reset':False,
         u'pin_y2_description':u'none',
         u'is_on_stand':False,
         u'emer_heat_source':u'electric',
         u'filter_reminder_enabled':False,
         u'compressor_lockout_leaf':-17.8,
         u'$version':10702,
         u'aux_heat_delivery':u'forced-air',
         u'away_temperature_high':25.556,
         u'fan_duty_start_time':0,
         u'learning_days_completed_range':2,
         u'target_humidity_enabled':False,
         u'leaf_threshold_cool':23.98,
         u'sunlight_correction_ready':True,
         u'fan_timer_timeout':0,
         u'has_dual_fuel':False,
         u'safety_temp_activating_hvac':False,
         u'dual_fuel_selected':False,
         u'heatpump_setback_active':False,
         u'has_heat_pump':False,
         u'fan_control_state':False,
         u'model_version':u'Display-2.8',
         u'has_aux_heat':False,
         u'current_version':u'4.2.5',
         u'away_temperature_high_enabled':True,
         u'alt_heat_delivery':u'forced-air',
         u'current_humidity':33,
         u'target_humidity':35.0,
         u'upper_safety_temp':35.0,
         u'heater_delivery':u'forced-air',
         u'preconditioning_ready':True,
         u'backplate_mono_version':u'4.0.26',
         u'has_fossil_fuel':True,
         u'mac_address':u'18b4300bbaef',
         u'cooling_source':u'electric',
         u'type':u'TBD',
         u'lower_safety_temp':4.444,
         u'emer_heat_delivery':u'forced-air',
         u'humidity_control_lockout_start_time':0,
         u'creation_time':1389478233615         L,
         u'fan_mode':u'auto',
         u'filter_changed_set_date':0,
         u'range_enable':True,
         u'heatpump_savings':u'off',
         u'radiant_control_enabled':False,
         u'temperature_lock_low_temp':20.0,
         u'where_id':u'00000000-0000-0000-0000-000100000006',
         u'pin_ob_description':u'none',
         u'alt_heat_x2_delivery':u'forced-air',
         u'humidity_control_lockout_enabled':False,
         u'fan_duty_cycle':3600,
         u'heatpump_ready':False,
         u'preconditioning_enabled':False,
         u'target_time_confidence':0.0,
         u'click_sound':u'on',
         u'pin_w1_description':u'heat',
         u'has_air_filter':True,
         u'auto_dehum_state':False,
         u'cooling_x2_source':u'electric',
         u'temperature_lock_high_temp':22.222,
         u'heat_pump_aux_threshold':10.0,
         u'rssi':71.0,
         u'has_emer_heat':False,
         u'has_alt_heat':False,
         u'leaf_schedule_delta':1.11,
         u'backplate_bsl_version':u'2.1',
         u'user_brightness':u'medium',
         u'preconditioning_active':False,
         u'pin_w2aux_description':u'none',
         u'pin_rc_description':u'none',
         u'has_dehumidifier':False,
         u'maint_band_upper':0.56,
         u'leaf_learning':u'ready',
         u'pin_y1_description':u'cool',
         u'capability_level':4.0,
         u'available_locales':u'en_US,
         fr_CA,
         es_US,
         en_GB,
         fr_FR,
         nl_NL',
         u'dehumidifier_state':False,
         u'dehumidifier_type':u'unknown',
         u'nlclient_state':u'',
         u'upper_safety_temp_enabled':False,
         u'learning_state':u'slow',
         u'time_to_target_training':u'ready',
         u'fan_cooling_state':False,
         u'fan_duty_end_time':0,
         u'alt_heat_source':u'gas',
         u'$timestamp':1410878148994         L,
         u'heat_link_connection':0,
         u'temperature_lock_pin_hash':u'',
         u'cooling_delivery':u'unknown',
         u'heat_pump_aux_threshold_enabled':True,
         u'leaf_away_low':16.67,
         u'heat_x3_delivery':u'forced-air',
         u'ob_orientation':u'O',
         u'touched_by':{

         },
         u'temperature_scale':u'F',
         u'emer_heat_enable':False,
         u'backplate_mono_info':         u'TFE (BP_D2) 4.0.26 (root@bamboo) 2014-07-02 14:37:01         ', u'         auto_away_enable':True,
         u'pin_g_description':u'fan',
         u'local_ip':u'10.0.0.124',
         u'has_x2_heat':False,
         u'away_temperature_low':10.0,
         u'time_to_target':0,
         u'heat_x2_delivery':u'forced-air',
         u'learning_days_completed_heat':184,
         u'dual_fuel_breakpoint':-1.0,
         u'heater_source':u'gas',
         u'pin_c_description':u'power'
      }
   },
   u'shared':{
      u'02AA01AC371305HK':{
         u'hvac_ac_state':False,
         u'compressor_lockout_timeout':0,
         u'hvac_alt_heat_x2_state':False,
         u'compressor_lockout_enabled':False,
         u'target_temperature':26.667,
         u'auto_away':0,
         u'can_heat':True,
         u'hvac_aux_heater_state':False,
         u'target_change_pending':False,
         u'hvac_heat_x2_state':False,
         u'target_temperature_low':20.0,
         u'target_temperature_high':24.0,
         u'hvac_heat_x3_state':False,
         u'hvac_cool_x2_state':False,
         u'$timestamp':1410881488607         L,
         u'hvac_heater_state':False,
         u'auto_away_learning':u'ready',
         u'target_temperature_type':u'cool',
         u'touched_by':{

         },
         u'name':u'Nest',
         u'can_cool':True,
         u'hvac_fan_state':False,
         u'$version':30953,
         u'current_temperature':22.55,
         u'hvac_emer_heat_state':False,
         u'hvac_alt_heat_state':False
      }
   },
   u'message':{
      u'02AA01AC371305HK':{
         u'$version':2878,
         u'$timestamp':1389479071341         L
      }
   },
   u'metadata':{
      u'02AA01AC371305HK':{
         u'$version':-1,
         u'last_ip':u'127.0.0.1',
         u'last_connection':1356998400000         L,
         u'$timestamp':1356998400000         L
      }
   },
   u'where':{
      u'dbd0c390-7b0d-11e3-9da1-12313b0281cc':{
         u'$version':21392,
         u'wheres':[
            {
               u'where_id':u'00000000-0000-0000-0000-000100000001',
               u'name':u'Basement'
            },
            {
               u'where_id':u'00000000-0000-0000-0000-00010000000d',
               u'name':u'Bedroom'
            },
            {
               u'where_id':u'00000000-0000-0000-0000-000100000003',
               u'name':u'Den'
            },
            {
               u'where_id':u'00000000-0000-0000-0000-000100000010',
               u'name':u'Dining Room'
            },
            {
               u'where_id':u'00000000-0000-0000-0000-000100000006',
               u'name':u'Downstairs'
            },
            {
               u'where_id':u'00000000-0000-0000-0000-000100000000',
               u'name':u'Entryway'
            },
            {
               u'where_id':u'00000000-0000-0000-0000-00010000000b',
               u'name':u'Family Room'
            },
            {
               u'where_id':u'00000000-0000-0000-0000-000100000002',
               u'name':u'Hallway'
            },
            {
               u'where_id':u'00000000-0000-0000-0000-000100000008',
               u'name':u'Kids Room'
            },
            {
               u'where_id':u'00000000-0000-0000-0000-00010000000a',
               u'name':u'Kitchen'
            },
            {
               u'where_id':u'00000000-0000-0000-0000-00010000000c',
               u'name':u'Living Room'
            },
            {
               u'where_id':u'00000000-0000-0000-0000-000100000005',
               u'name':u'Master Bedroom'
            },
            {
               u'where_id':u'00000000-0000-0000-0000-00010000000e',
               u'name':u'Office'
            },
            {
               u'where_id':u'00000000-0000-0000-0000-00010000000f',
               u'name':u'Upstairs'
            }
         ],
         u'$timestamp':1389478520396         L
      }
   },
   u'structure':{
      u'dbd0c390-7b0d-11e3-9da1-12313b0281cc':{
         u'num_thermostats':u'unknown',
         u'away_timestamp':1389737117,
         u'clutches':[

         ],
         u'name':u'',
         u'hvac_safety_shutoff_enabled':True,
         u'renovation_date':u'unknown',
         u'away':False,
         u'creation_time':1389478520396         L,
         u'devices':[
            u'device.02AA01AC371305HK'
         ],
         u'topaz_enhanced_auto_away_enabled':False,
         u'touched_by':{

         },
         u'fabric_ids':[

         ],
         u'postal_code':u'99208',
         u'user':u'user.604854',
         u'country_code':u'US',
         u'$version':-14065,
         u'house_type':u'family',
         u'dr_reminder_enabled':True,
         u'away_setter':1,
         u'swarm':[
            u'device.02AA01AC371305HK'
         ],
         u'$timestamp':1410642710997         L
      }
   },
   u'utility':{
      u'dbd0c390-7b0d-11e3-9da1-12313b0281cc':{
         u'$version':-1,
         u'$timestamp':1
      }
   }
}